feature: selecting a sensible terminal, configurable terminal command, and notifying when we can't open it
mattkae/miracle-wm pull request #40
Opened 2024-02-25 15:12 UTC by mattkae

## What's new?
- We now select a sensible terminal if you've fully installed the snap or the binary (e.g. `sudo make install`). The sensible terminal command needs to be found in your path
- Alternatively, you may specify a terminal command via the `terminal: MY_COMMAND_STRING` key in the config file
- If we fail to launch your terminal, we'll notify you via `libnotify`

2024-02-25 16:55 UTC, OPNA2608 requested changes
Tested by applying onto 0.1.0. Terminal command works now, as does overriding it with a command in the config. Haven't checked the notifying part.

Just one suggestion about install location, now that the GNUInstallDirs PR was merged.

2024-02-25 16:55 UTC, OPNA2608 commented on CMakeLists.txt
> +    DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
```suggestion
    DESTINATION ${CMAKE_INSTALL_BINDIR}
```

2024-02-25 18:41 UTC, mattkae commented on CMakeLists.txt
> +    DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
Agreed!

2024-02-25 18:44 UTC, mattkae commented
> Haven't checked the notifying part.

I'm just using `libnotify` there, so I _imagine_ it's present almost everywhere. LMK if you have any info to think otherwise

2024-02-26 09:31 UTC, OPNA2608 commented on src/miracle_config.cpp
> +    );
Don't know if it would make sense to ensure that `name` length doesn't exceed however much space is left in `buffer` *after* everything else, otherwise a long `name` could cut off parts (or the entirety) of `> /dev/null 2>&1`.

2024-02-26 18:34 UTC, mattkae commented on src/miracle_config.cpp
> +    );
Sounds good to me!

2024-02-26 18:48 UTC, merged