Almost working!
mattkae/miracle-wm pull request #73
Opened 2024-03-28 22:34 UTC by mattkae

2024-04-01 12:54 UTC, Conan-Kudo requested changes

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +License:        GPL0-3.0
Is it `GPL-3.0-only` or `GPL-3.0-or-later`? I can't find anything that specifies one or the other in the code or documentation.

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildArch:      x86_64
Drop this. We don't need it.

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  mir-devel, cmake, g++, glib2, glib2-devel, yaml-cpp-devel, libevdev-devel, json-devel, libnotify-devel, gtest, gtest-devel, libxkbcommon-devel
List this one per line, and also try to prefer the actual names they are requested from CMake...

For example, if you're requesting something by a pkgconfig name, use `pkgconfig(foo)` deps, and if you're requesting something by their CMake name, use `cmake(Foo)` deps.

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +miracle-wm is a Wayland compositor based on Mir. It features a tiling window manager at its core, very much in the style of i3 and sway. The intention is to build a compositor that is flashier and mo
Wrap at 79 columns.

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +rm -rf *
Drop this, it already happens implicitly

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +%global __brp_check_rpaths %{nil}
Drop this.

2024-04-01 12:54 UTC, Conan-Kudo commented on session/usr/local/share/wayland-sessions/miracle-wm-non-snap.desktop.in
> +Name=Miracle (bin)
Drop the suffix. Also this should be the default name `miracle-wm.desktop.in` and the snap version should be `miracle-wm-snap.desktop.in`.

2024-04-01 12:54 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +Summary:        miracle-wm is a tiling Wayland compositor based on Mir
Don't include the name of the thing itself.

2024-04-01 13:22 UTC, mattkae commented on rpm/miracle-wm.spec
> +License:        GPL0-3.0
I can do "or later"

2024-04-01 13:37 UTC, mattkae commented on rpm/miracle-wm.spec
> +BuildRequires:  mir-devel, cmake, g++, glib2, glib2-devel, yaml-cpp-devel, libevdev-devel, json-devel, libnotify-devel, gtest, gtest-devel, libxkbcommon-devel
What's the format here?

```
BuildRequires: mir-devel
BuildRequires: cmake
...
```

2024-04-01 14:03 UTC, mattkae commented on rpm/miracle-wm.spec
> +BuildRequires:  mir-devel, cmake, g++, glib2, glib2-devel, yaml-cpp-devel, libevdev-devel, json-devel, libnotify-devel, gtest, gtest-devel, libxkbcommon-devel
Kk, I believe that I've done this right!

2024-04-01 15:48 UTC, Conan-Kudo requested changes

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  gtest-devel
This is redundant.

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  mir-devel
It looks like the CMakeLists requests MirAL via pkgconfig, so this should be `pkgconfig(miral)`.

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  glib2-devel
This is redundant.

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  yaml-cpp-devel
This can be replaced with `pkgconfig(yaml-cpp)`

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  libevdev-devel
This can be replaced with `pkgconfig(libevdev)`

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  json-devel
This can be replaced with `cmake(nlohmann_json) >= 3.2.0`

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  libnotify-devel
This can be replaced with `pkgconfig(libnotify)`

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  libxkbcommon-devel
What requires this? It's not present in the CMakeLists anywhere I can find.

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +- First Test
Wrong changelog format: https://docs.fedoraproject.org/en-US/packaging-guidelines/manual-changelog/

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +Version:        0.0.1
Shouldn't this be a higher version?

2024-04-01 15:48 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +Source0:        %{name}-%{version}.tar.gz
This should be a SourceURL ideally: https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/#_git_tags

2024-04-01 16:10 UTC, Conan-Kudo requested changes

2024-04-01 16:10 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +License:        GPLv3+
This needs to be a SPDX identifier, thus `GPL-3.0-or-later`.

2024-04-01 18:18 UTC, mattkae commented on rpm/miracle-wm.spec
> +BuildRequires:  libxkbcommon-devel
I forget exactly, but I ran into this requirement when building. Perhaps it's somewhere in Mir

2024-04-01 18:20 UTC, mattkae commented on rpm/miracle-wm.spec
> +Version:        0.0.1
I am going to leave it as `0.0.1` for the initial release, since I'm in between a bunch of things right now. And then when I officially release 0.2.0 later this month, I will bump them all at once. I wouldn't even call it a `0.2.0` beta since I'm waiting on a Mir relase ATM

2024-04-01 18:23 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +Source0:        %{name}-%{version}.tar.gz
No. rpmbuild doesn't download, it just makes it so `rpmdev-spectool` can parse the URL to download. `rpmbuild` itself ignores the URL parts and just reads the last component/basename to identify the file.

2024-04-01 18:36 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +BuildRequires:  libxkbcommon-devel
This might be a bug then in Mir, the pkgconfig stuff should already declare it requires `xkbcommon` so that it gets pulled in automatically.

2024-04-02 16:49 UTC, Conan-Kudo requested changes
One small thing

2024-04-02 19:09 UTC, merged