bugfix: response to requests on rpm package
mattkae/miracle-wm pull request #77
Opened 2024-04-04 22:07 UTC by mattkae

## What's new?
- Added license headers to all of the source code files
- Added a `desktop-file-validate` line to the spec file
- Running tests in the spec file
- Added CI for fedora that builds the source rpm

2024-04-10 15:57 UTC, Conan-Kudo approved these changes

2024-04-10 15:59 UTC, Conan-Kudo requested changes

2024-04-10 15:59 UTC, Conan-Kudo commented on rpm/miracle-wm.spec
> +%{__cmake_builddir}/bin/miracle-wm-tests
Don't do this. You should probably wire this up into `ctest` so that it can be invoked via `%ctest` macro.

Alternatively, you can do:

`%{_vpath_builddir}/bin/miracle-wm-tests`

2024-04-10 21:51 UTC, mattkae commented on rpm/miracle-wm.spec
> +%{__cmake_builddir}/bin/miracle-wm-tests
Kk I did the alternate since it works out of the box with what i have here

2024-04-10 21:57 UTC, Conan-Kudo approved these changes

2024-04-10 22:17 UTC, Conan-Kudo requested changes

2024-04-10 22:17 UTC, Conan-Kudo commented on .github/workflows/fedora-rpm.yml
> +              echo 'RUN rpmbuild -bs ~/rpmbuild/SPECS/miracle-wm.spec'
Maybe do this instead?

```suggestion
              echo 'FROM fedora:rawhide'
              echo '# set TZ to ensure the test using timestamp'
              echo 'RUN dnf install -y mock mock-core-configs distribution-gpg-keys'
              echo 'COPY miracle-wm miracle-wm-0.1.0'
              echo 'RUN chmod -R a+rwx miracle-wm-0.1.0'
              echo 'RUN tar --create --file miracle-wm-0.1.0.tar.gz miracle-wm-0.1.0'
              echo 'RUN mock --isolation=simple --root=fedora-40-x86_64 --sources . --spec miracle-wm-0.1.0/rpm/miracle-wm.spec' 
```

This mimics how the package is built in Fedora itself.

2024-04-11 11:55 UTC, mattkae commented on .github/workflows/fedora-rpm.yml
> +              echo 'RUN rpmbuild -bs ~/rpmbuild/SPECS/miracle-wm.spec'
Let's try it out!

2024-04-11 12:28 UTC, mattkae commented on .github/workflows/fedora-rpm.yml
> +              echo 'RUN rpmbuild -bs ~/rpmbuild/SPECS/miracle-wm.spec'
Eh, no dice. Not going to spend any more time on the CI though for now. The main thing here was feedback on the package request :)

2024-04-11 12:31 UTC, merged