Try to find missing gfx-drivers with CMake #72
mattkae/miracle-wm pull request #94
Opened 2024-04-18 03:43 UTC by spongythecake

This commit brings an extra library check in CMakeLists.txt related to mir graphics drivers desktop. A hardcoded known-library-list was introduced and used with find_library. Also, the build output informs the user of the missing libraries. Fixes #72

2024-04-18 03:48 UTC, spongythecake commented
I decided to raise the warning to a normal status, since you might be interested in building without graphics involved. 

Another mention, I allowed the libraries detected to be saved as a cmake cache variable. I made this decision since it might be good insight for future bug reports(!?). I'll leave the rest to you!

2024-04-19 11:44 UTC, mattkae requested changes
Awesome stuff @spongythecake ! I just have two questions for future-proofing this thing. You can also check CI to see it working :smile:

2024-04-19 11:44 UTC, mattkae commented on CMakeLists.txt
> +)
Out of curiosity, are we able to wildcard these values, e.g. `graphics-eglstream-kms.so.*`? That would be nice for future-proofing this thing!

2024-04-19 11:44 UTC, mattkae commented on CMakeLists.txt
> +        PATH /usr/lib/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu/mir/server-platform
Do we need to provide the whole path here? Would cmaek not look in the regular `LD_LIBRARY_PATHS` for us?

2024-04-19 16:08 UTC, Conan-Kudo commented
It might make sense to have Mir export CMake config modules for the platforms instead, because this is likely to be quite brittle.

2024-04-19 16:09 UTC, Conan-Kudo commented on CMakeLists.txt
> +        PATH /usr/lib/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu/mir/server-platform
And the path would be wrong on non-Debian platforms anyway.

2024-04-19 18:22 UTC, Conan-Kudo commented on CMakeLists.txt
> +        PATH /usr/lib/${CMAKE_SYSTEM_PROCESSOR}-linux-gnu/mir/server-platform
So would Fedora and everyone else. Only Debian and Ubuntu use that path model.

2024-04-22 15:50 UTC, mattkae commented on CMakeLists.txt
> +)
Gotcha, then I am okay with having a non-wildcard in this scenario :smile:

2024-04-23 21:14 UTC, spongythecake commented on CMakeLists.txt
> +)
OK, I can run with this! 

Additionally, I need to fix the paths for non-debian and Busybox machines. So, as a wise cyborg once said, "I'll be back".

2024-04-25 18:41 UTC, mattkae commented
@Conan-Kudo Ah I see what you mean better now. Perhaps something like this _does_ belong in the Mir project now that I've thought about it. Mir already provides some facilities for find package. It would be really nice if it also provided some facilities to find the platform packages as well. I will make a ticket over there

2024-04-25 18:45 UTC, mattkae commented
Sorry for all the back and forth @spongythecake ! I believe @Conan-Kudo is right here after thinking about it. I opened up this bug in _Mir_: https://github.com/canonical/mir/issues/3352

I'll be curious to hear what the rest of the team would think about this before acting on it, but it seems to be a good solution to fix miracle-wm any any other Mir-based compositor that runs into this issue in the future.

2024-04-26 08:16 UTC, spongythecake commented
> Sorry for all the back and forth @spongythecake ! I believe @Conan-Kudo is right here after thinking about it. I opened up this bug in _Mir_: [canonical/mir#3352](https://github.com/canonical/mir/issues/3352)
> 
> I'll be curious to hear what the rest of the team would think about this before acting on it, but it seems to be a good solution to fix miracle-wm any any other Mir-based compositor that runs into this issue in the future.

I want miracle-wm to be the best it can! I also appreciated the updates.

2024-06-12 19:41 UTC, mattkae commented
Closing this since we've got that ticket made in Mir ;) But thanks for bringing that issue to light!

2024-06-12 19:41 UTC, closed without merging